source 'https://rubygems.org'

gem 'jekyll', '2.4.0'
#gem 'github-pages', '40'
gem 'pygments.rb', '0.6.3'
gem 'yajl-ruby', '1.2.0'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'